In [2]:
!pip install catboost


from google.colab import drive
drive.mount('./gdrive')
from pathlib import Path

data_dir = Path('/content/gdrive/MyDrive/MAIL')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: catboost in /usr/local/lib/python3.7/dist-packages (1.0.6)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.7.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2022.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.4.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->catboost) (4.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (8.0.1)
Drive already mounted at ./gdrive; to attempt to forcibly remount, call drive.mount("./gdrive", force_remount=True).

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
import pandas as pd
from sklearn.metrics import *
from catboost import CatBoostClassifier
import numpy as np
from sklearn.model_selection import StratifiedKFold


warnings.filterwarnings('ignore')

def seed_everything(seed: int):
    import random, os
    import numpy as np
    import torch
    
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True
    
seed_everything(42)

In [4]:
raw_data = pd.read_csv(data_dir / 'train_id.csv', index_col=0)
vals = raw_data.Data.apply(eval)
res = [val if len(val) == 240 else val + [0] * (240 - len(val)) for val in vals]
vals1 = raw_data.Data_2.apply(eval)
res1 = [val if len(val) == 240 else val + [0] * (240 - len(val)) for val in vals1]

df_1 = pd.DataFrame(res).add_prefix('data')
df_2 = pd.DataFrame(res1).add_prefix('data_new')

additional_data = pd.concat((df_1, df_2), axis=1)

In [5]:
tt = pd.concat((additional_data, raw_data), axis=1)

In [6]:
train_feat, test_feat = train_test_split(tt, random_state=142, test_size=0.2, stratify=raw_data.Class_label)
train_feat.reset_index(drop=True)

,data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,...,data_new238,data_new239,Filename,Test_index,Presentation,Question,Data,Data_2,Class_label,id
0,-41,-62,-49,-26,-15,-6,7,22,43,63,...,-728,-817,80508871-29ee-4d07-8b0a-e563731ce6d1,1,3,2,"[-41, -62, -49, -26, -15, -6, 7, 22, 43, 63, 3...","[-704, -743, -729, -702, -689, -678, -663, -64...",2,262
1,-1000,-1178,-1134,-984,-885,-860,-837,-774,-587,-594,...,884,479,f0e0b261-352b-4207-b906-afdae32afa6a,2,3,11,"[-1000, -1178, -1134, -984, -885, -860, -837, ...","[-1589, -1974, -1994, -1793, -1638, -1633, -16...",1,165
2,-734,-692,-654,-621,-559,-480,-404,-339,-280,-234,...,-766,-709,4ab63cfc-7291-4c7c-a4c8-437212605677,0,1,9,"[-734, -692, -654, -621, -559, -480, -404, -33...","[-1491, -1419, -1377, -1358, -1287, -1187, -11...",1,319
3,-78,-61,-42,-45,-59,-66,-50,-16,19,34,...,1150,1130,12555fb4-ea91-428f-955e-bc84d4e5cb74,2,2,8,"[-78, -61, -42, -45, -59, -66, -50, -16, 19, 3...","[868, 825, 791, 794, 813, 812, 775, 697, 623, ...",1,293
4,-202,-148,-132,-89,-20,61,138,196,80,-325,...,118,162,73d5adee-c1ec-46b3-a519-ccf381293116,0,3,4,"[-202, -148, -132, -89, -20, 61, 138, 196, 80,...","[-123, -95, -81, -33, 35, 101, 154, 186, 28, -...",0,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25101,-41,-73,-86,-86,-81,-78,-77,-73,-60,-44,...,-335,-293,07f86761-78ba-4d41-af89-3bdbbfec2b00,0,1,8,"[-41, -73, -86, -86, -81, -78, -77, -73, -60, ...","[-495, -537, -558, -558, -548, -542, -538, -53...",1,236
25102,54,65,76,86,89,-60,-148,-144,-103,-77,...,558,517,fcbe8631-e21c-41d6-975f-6de80d663bcf,2,3,9,"[54, 65, 76, 86, 89, -60, -148, -144, -103, -7...","[1088, 1032, 979, 914, 1011, 1451, 1584, 1565,...",0,283
25103,803,807,830,853,865,878,893,908,919,927,...,-416,-478,0cc70727-e962-49ef-a3f2-c3956bc7100b,3,2,2,"[803, 807, 830, 853, 865, 878, 893, 908, 919, ...","[-102, -96, -206, -348, -424, -502, -582, -652...",2,227
25104,-447,-438,-421,-404,-390,-374,-361,-356,-395,-471,...,72,20,265036e7-5434-4417-a116-e28ea903e1c7,0,3,5,"[-447, -438, -421, -404, -390, -374, -361, -35...","[-18, -19, -21, -22, -22, -22, -24, -24, -16, ...",1,150
25105,-290,-201,-171,-198,-243,-274,-288,-311,-361,-412,...,87,9,5dfcc252-14d0-4643-9814-2dadec48c2f3,3,3,0,"[-290, -201, -171, -198, -243, -274, -288, -31...","[-192, -196, -151, -102, -77, -78, -79, -51, -...",0,20

In [7]:
def drop_smth(df):
  df = df.drop('id', axis=1)
  df = df.drop('Data', axis=1)
  df = df.drop('Data_2', axis=1)
  df = df.drop('Filename', axis=1)
  return df
train_feat = drop_smth(train_feat)
test_feat = drop_smth(test_feat)

In [8]:
train_feat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25106 entries, 16833 to 4677
Columns: 484 entries, data0 to Class_label
dtypes: int64(484)
memory usage: 92.9 MB

In [346]:
print("Train_feat: ",train_feat.shape)

Train_feat:  (25106, 484)
gen_feat_data:  (23885, 240)
gen_feat_data_2:  (23885, 240)

In [19]:

params = {
    "loss_function": "MultiClass",
    "verbose": 100,
    'eval_metric': 'TotalF1',
    'use_best_model': True, 
    'early_stopping_rounds': 300,
    'iterations': 4000,
    # 'eval_metric': 'TotalF1',
}


def oof_fit(data):
    kf = StratifiedKFold(n_splits=2, random_state=142, shuffle=True)
    models = []
    ginnis = []
    for train_ids, val_ids in kf.split(data.drop('Class_label', axis=1), data.Class_label):
        train_x, train_y = data.iloc[train_ids].drop('Class_label', axis=1), data.iloc[train_ids].Class_label
        val_x, val_y = data.iloc[val_ids].drop('Class_label', axis=1), data.iloc[val_ids].Class_label
        
        model = CatBoostClassifier(**params)
        model.fit(train_x, train_y, eval_set=(val_x, val_y))
        models.append(model)
        roc = roc_auc_score(val_y, model.predict_proba(val_x),multi_class='ovr')
        ginnis.append(roc * 2 - 1)
        print(f"MultiClass = {ginnis[-1]}")
    print(f"Mean ginny = {np.mean(ginnis)}")
    return models

In [10]:
models = oof_fit(train_feat)

Learning rate set to 0.114236
0:	learn: 0.4054399	test: 0.4043941	best: 0.4043941 (0)	total: 837ms	remaining: 13m 56s
100:	learn: 0.4139821	test: 0.4052252	best: 0.4057922 (98)	total: 53.1s	remaining: 7m 53s
200:	learn: 0.4748927	test: 0.4102950	best: 0.4108956 (193)	total: 1m 50s	remaining: 7m 19s
300:	learn: 0.5428979	test: 0.4153814	best: 0.4156389 (286)	total: 2m 41s	remaining: 6m 14s
400:	learn: 0.6129964	test: 0.4259310	best: 0.4275478 (378)	total: 3m 40s	remaining: 5m 28s
500:	learn: 0.6772940	test: 0.4336791	best: 0.4337029 (498)	total: 4m 21s	remaining: 4m 20s
600:	learn: 0.7286912	test: 0.4401198	best: 0.4401198 (600)	total: 5m 2s	remaining: 3m 21s
700:	learn: 0.7711744	test: 0.4456709	best: 0.4469882 (695)	total: 6m 4s	remaining: 2m 35s
800:	learn: 0.8070514	test: 0.4502387	best: 0.4505514 (799)	total: 6m 56s	remaining: 1m 43s
900:	learn: 0.8376088	test: 0.4495266	best: 0.4511421 (892)	total: 7m 41s	remaining: 50.7s
999:	learn: 0.8637859	test: 0.4541509	best: 0.4541509 (999)	total: 8m 22s	remaining: 0us

bestTest = 0.4541508566
bestIteration = 999

MultiClass = 0.11675935114729352
Learning rate set to 0.114236
0:	learn: 0.4055365	test: 0.4058974	best: 0.4058974 (0)	total: 571ms	remaining: 9m 30s
100:	learn: 0.4155620	test: 0.4046557	best: 0.4058974 (0)	total: 48.9s	remaining: 7m 14s
200:	learn: 0.4756974	test: 0.4116218	best: 0.4116218 (200)	total: 1m 28s	remaining: 5m 51s
300:	learn: 0.5481573	test: 0.4207610	best: 0.4207610 (300)	total: 2m 8s	remaining: 4m 57s
400:	learn: 0.6198229	test: 0.4270469	best: 0.4282169 (388)	total: 2m 50s	remaining: 4m 14s
500:	learn: 0.6815521	test: 0.4324435	best: 0.4327962 (495)	total: 3m 31s	remaining: 3m 30s
600:	learn: 0.7306855	test: 0.4404569	best: 0.4408801 (593)	total: 4m 12s	remaining: 2m 47s
700:	learn: 0.7721634	test: 0.4460254	best: 0.4471853 (698)	total: 5m 12s	remaining: 2m 13s
800:	learn: 0.8033565	test: 0.4488568	best: 0.4497195 (799)	total: 5m 59s	remaining: 1m 29s
900:	learn: 0.8358493	test: 0.4556204	best: 0.4556204 (900)	total: 6m 43s	remaining: 44.3s
999:	learn: 0.8583659	test: 0.4583708	best: 0.4590844 (992)	total: 7m 23s	remaining: 0us

bestTest = 0.4590843847
bestIteration = 992

Shrink model to first 993 iterations.
MultiClass = 0.1458174937603247
Learning rate set to 0.114236
0:	learn: 0.4048807	test: 0.4044666	best: 0.4044666 (0)	total: 693ms	remaining: 11m 31s
100:	learn: 0.4144888	test: 0.4053920	best: 0.4053920 (100)	total: 40.5s	remaining: 6m
200:	learn: 0.4641553	test: 0.4107048	best: 0.4111613 (194)	total: 1m 21s	remaining: 5m 25s
300:	learn: 0.5422990	test: 0.4195460	best: 0.4195460 (300)	total: 2m 2s	remaining: 4m 43s
400:	learn: 0.6124531	test: 0.4282716	best: 0.4287493 (394)	total: 2m 42s	remaining: 4m 2s
500:	learn: 0.6807171	test: 0.4343473	best: 0.4345664 (499)	total: 3m 25s	remaining: 3m 24s
600:	learn: 0.7341387	test: 0.4421897	best: 0.4426836 (571)	total: 4m 6s	remaining: 2m 43s
700:	learn: 0.7767995	test: 0.4504645	best: 0.4509861 (698)	total: 4m 49s	remaining: 2m 3s
800:	learn: 0.8142920	test: 0.4536278	best: 0.4536335 (789)	total: 5m 30s	remaining: 1m 22s
900:	learn: 0.8456767	test: 0.4561002	best: 0.4575437 (891)	total: 6m 12s	remaining: 40.9s
999:	learn: 0.8675245	test: 0.4565935	best: 0.4586454 (964)	total: 6m 55s	remaining: 0us

bestTest = 0.4586453611
bestIteration = 964

Shrink model to first 965 iterations.
MultiClass = 0.11024664432534514
Mean ginny = 0.1242744964109878

In [12]:
y_pred = models[-1].predict(test_feat.drop('Class_label', axis=1))
y_val = test_feat.Class_label
df=pd.DataFrame({'Actual': y_val, 'Predicted':y_pred.ravel()})
df

       Actual  Predicted
20412       1          1
30783       0          1
11979       2          1
26905       0          0
16614       0          1
...       ...        ...
2432        1          1
28846       1          1
5541        1          1
7825        0          1
28834       0          1

[6277 rows x 2 columns]

In [13]:
import collections

print(collections.Counter(y_val))
print(collections.Counter(y_pred.ravel()))

Counter({1: 3528, 2: 1406, 0: 1343})
Counter({1: 5737, 2: 290, 0: 250})

In [14]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_val, y_pred)

confmtrx = np.array(confusion_matrix(y_val, y_pred))
pd.DataFrame(confmtrx, index=['0','1', '2'],
columns=['0', '1', '2'])

     0     1    2
0  112  1196   35
1   99  3282  147
2   39  1259  108

In [15]:
import sklearn.metrics as metrics
from sklearn.metrics import classification_report

print('Accuracy Score:', metrics.accuracy_score(y_val, y_pred))  
#Create classification report
class_report=classification_report(y_val, y_pred)
print(class_report)

Accuracy Score: 0.5579098295364028
              precision    recall  f1-score   support

           0       0.45      0.08      0.14      1343
           1       0.57      0.93      0.71      3528
           2       0.37      0.08      0.13      1406

    accuracy                           0.56      6277
   macro avg       0.46      0.36      0.33      6277
weighted avg       0.50      0.56      0.46      6277

In [16]:
from sklearn.metrics import f1_score
print(f1_score(y_val, y_pred, average='macro'))

0.32548214297520356

In [ ]:
models1 = oof_fit(train_feat)

Learning rate set to 0.066883
0:	learn: 0.4071483	test: 0.4055292	best: 0.4055292 (0)	total: 544ms	remaining: 36m 14s
100:	learn: 0.4056967	test: 0.4045812	best: 0.4055292 (0)	total: 37.8s	remaining: 24m 19s
200:	learn: 0.4282198	test: 0.4055791	best: 0.4059743 (195)	total: 1m 15s	remaining: 23m 38s
300:	learn: 0.4793608	test: 0.4096133	best: 0.4103599 (290)	total: 1m 54s	remaining: 23m 23s
400:	learn: 0.5321748	test: 0.4151804	best: 0.4151804 (400)	total: 2m 32s	remaining: 22m 45s
500:	learn: 0.5909714	test: 0.4200017	best: 0.4200068 (498)	total: 3m 10s	remaining: 22m 9s
600:	learn: 0.6399978	test: 0.4252988	best: 0.4254618 (570)	total: 3m 50s	remaining: 21m 42s
700:	learn: 0.6881591	test: 0.4325006	best: 0.4327061 (697)	total: 4m 28s	remaining: 21m 3s
800:	learn: 0.7286257	test: 0.4372725	best: 0.4375358 (772)	total: 5m 6s	remaining: 20m 24s
900:	learn: 0.7657582	test: 0.4376910	best: 0.4379446 (893)	total: 5m 46s	remaining: 19m 52s
1000:	learn: 0.7990069	test: 0.4394100	best: 0.4395354 (985)	total: 6m 25s	remaining: 19m 14s
1100:	learn: 0.8230616	test: 0.4424613	best: 0.4430510 (1093)	total: 7m 3s	remaining: 18m 35s
1200:	learn: 0.8446119	test: 0.4452027	best: 0.4462238 (1186)	total: 7m 44s	remaining: 18m 2s
1300:	learn: 0.8629477	test: 0.4459656	best: 0.4464237 (1296)	total: 8m 22s	remaining: 17m 23s
1400:	learn: 0.8796763	test: 0.4472305	best: 0.4492312 (1349)	total: 9m 1s	remaining: 16m 44s
1500:	learn: 0.8977940	test: 0.4504585	best: 0.4510890 (1473)	total: 9m 42s	remaining: 16m 9s
1600:	learn: 0.9127739	test: 0.4532879	best: 0.4536374 (1587)	total: 10m 20s	remaining: 15m 30s
1700:	learn: 0.9235739	test: 0.4520799	best: 0.4538168 (1623)	total: 10m 59s	remaining: 14m 50s
1800:	learn: 0.9349366	test: 0.4545575	best: 0.4550985 (1797)	total: 11m 39s	remaining: 14m 14s
1900:	learn: 0.9439583	test: 0.4544212	best: 0.4559187 (1871)	total: 12m 17s	remaining: 13m 34s
2000:	learn: 0.9507132	test: 0.4558864	best: 0.4569923 (1972)	total: 12m 55s	remaining: 12m 55s
2100:	learn: 0.9564794	test: 0.4579056	best: 0.4584914 (2088)	total: 13m 36s	remaining: 12m 18s
2200:	learn: 0.9615846	test: 0.4585132	best: 0.4597102 (2128)	total: 14m 15s	remaining: 11m 38s
2300:	learn: 0.9654614	test: 0.4578304	best: 0.4599532 (2230)	total: 14m 53s	remaining: 11m
2400:	learn: 0.9702219	test: 0.4606558	best: 0.4608869 (2397)	total: 15m 34s	remaining: 10m 22s
2500:	learn: 0.9734394	test: 0.4616105	best: 0.4616105 (2500)	total: 16m 13s	remaining: 9m 43s
2600:	learn: 0.9767345	test: 0.4623646	best: 0.4627039 (2599)	total: 16m 52s	remaining: 9m 4s
2700:	learn: 0.9785036	test: 0.4627165	best: 0.4633728 (2609)	total: 17m 32s	remaining: 8m 26s
2800:	learn: 0.9817114	test: 0.4634103	best: 0.4637530 (2714)	total: 18m 11s	remaining: 7m 47s
2900:	learn: 0.9837923	test: 0.4623061	best: 0.4638273 (2821)	total: 18m 50s	remaining: 7m 8s
3000:	learn: 0.9854735	test: 0.4633625	best: 0.4645121 (2981)	total: 19m 31s	remaining: 6m 30s
3100:	learn: 0.9863533	test: 0.4630192	best: 0.4645121 (2981)	total: 20m 10s	remaining: 5m 50s
3200:	learn: 0.9878720	test: 0.4640895	best: 0.4645602 (3197)	total: 20m 51s	remaining: 5m 12s
3300:	learn: 0.9887506	test: 0.4632431	best: 0.4647850 (3252)	total: 21m 29s	remaining: 4m 33s
3400:	learn: 0.9896304	test: 0.4648995	best: 0.4648995 (3400)	total: 22m 7s	remaining: 3m 53s
3500:	learn: 0.9903496	test: 0.4636042	best: 0.4659714 (3433)	total: 22m 48s	remaining: 3m 15s
3600:	learn: 0.9912292	test: 0.4638046	best: 0.4659714 (3433)	total: 23m 27s	remaining: 2m 35s
3700:	learn: 0.9916282	test: 0.4637020	best: 0.4659714 (3433)	total: 24m 5s	remaining: 1m 56s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 0.4659713878
bestIteration = 3433

Shrink model to first 3434 iterations.
MultiClass = 0.12323174817628546
Learning rate set to 0.066883
0:	learn: 0.4066565	test: 0.4049822	best: 0.4049822 (0)	total: 537ms	remaining: 35m 48s
100:	learn: 0.4064117	test: 0.4046179	best: 0.4049822 (0)	total: 40s	remaining: 25m 44s
200:	learn: 0.4239463	test: 0.4049770	best: 0.4053409 (187)	total: 1m 17s	remaining: 24m 21s
300:	learn: 0.4667446	test: 0.4073464	best: 0.4074218 (299)	total: 1m 54s	remaining: 23m 28s
400:	learn: 0.5268976	test: 0.4114756	best: 0.4118244 (398)	total: 2m 34s	remaining: 23m 4s
500:	learn: 0.5840554	test: 0.4168530	best: 0.4171868 (491)	total: 3m 12s	remaining: 22m 22s
600:	learn: 0.6405875	test: 0.4207177	best: 0.4207430 (584)	total: 3m 50s	remaining: 21m 40s
700:	learn: 0.6880982	test: 0.4274179	best: 0.4275777 (695)	total: 4m 30s	remaining: 21m 12s
800:	learn: 0.7303544	test: 0.4285860	best: 0.4295177 (787)	total: 5m 9s	remaining: 20m 34s
900:	learn: 0.7696086	test: 0.4345615	best: 0.4345615 (900)	total: 5m 47s	remaining: 19m 55s
1000:	learn: 0.7992771	test: 0.4388420	best: 0.4388420 (1000)	total: 6m 28s	remaining: 19m 23s
1100:	learn: 0.8245601	test: 0.4414186	best: 0.4414186 (1100)	total: 7m 6s	remaining: 18m 43s
1200:	learn: 0.8477017	test: 0.4445440	best: 0.4446169 (1179)	total: 7m 46s	remaining: 18m 6s
1300:	learn: 0.8670975	test: 0.4460496	best: 0.4471311 (1288)	total: 8m 25s	remaining: 17m 29s
1400:	learn: 0.8827435	test: 0.4477235	best: 0.4483020 (1372)	total: 9m 4s	remaining: 16m 49s
1500:	learn: 0.8984120	test: 0.4494850	best: 0.4503997 (1486)	total: 9m 44s	remaining: 16m 12s
1600:	learn: 0.9131093	test: 0.4519201	best: 0.4527329 (1569)	total: 10m 22s	remaining: 15m 32s
1700:	learn: 0.9266415	test: 0.4524474	best: 0.4533091 (1662)	total: 11m	remaining: 14m 53s
1800:	learn: 0.9348645	test: 0.4527360	best: 0.4540843 (1764)	total: 11m 41s	remaining: 14m 16s
1900:	learn: 0.9419075	test: 0.4557546	best: 0.4557546 (1900)	total: 12m 20s	remaining: 13m 37s
2000:	learn: 0.9493404	test: 0.4551997	best: 0.4570688 (1959)	total: 12m 59s	remaining: 12m 58s
2100:	learn: 0.9551093	test: 0.4564754	best: 0.4570688 (1959)	total: 13m 39s	remaining: 12m 20s
2200:	learn: 0.9609411	test: 0.4567873	best: 0.4578752 (2111)	total: 14m 17s	remaining: 11m 41s
2300:	learn: 0.9661809	test: 0.4575678	best: 0.4592956 (2234)	total: 14m 56s	remaining: 11m 1s
2400:	learn: 0.9698980	test: 0.4585313	best: 0.4592956 (2234)	total: 15m 35s	remaining: 10m 23s
2500:	learn: 0.9731997	test: 0.4585600	best: 0.4594767 (2468)	total: 16m 14s	remaining: 9m 43s
2600:	learn: 0.9757692	test: 0.4585890	best: 0.4597036 (2537)	total: 16m 52s	remaining: 9m 4s

In [ ]:
def generate_features(df, 
                      feature_name="Data",
                      new_feature_name="gen_feature_",
                      feature_count=240):
  df[feature_name] = df[feature_name].str.replace("[", "")
  df[feature_name] = df[feature_name].str.replace("]", "")
    
  # new data frame with split value columns
  #new = df[feature_name].str.split(", ", n = feature_count, expand = True).astype(str).astype(int)
  #trans_names = [new_feature_name + feature_name + "_" + str(i) for i in range(0,feature_count)]
  #res = pd.DataFrame(new.values, columns=trans_names)
  #for column in res:
    #res[column] = res[column].to_numpy(dtype='int')

  res_df.isna().sum().max()
  return res.astype('int32')

def prepare_df(df):
  df['Test_index'] = df['Test_index'].to_numpy(dtype='int')
  df['Presentation'] = df['Presentation'].to_numpy(dtype='int')
  df['Question'] = df['Question'].to_numpy(dtype='int')
  df.drop(df[df.Data_2.str.count(",")==0].index, inplace=True)
  df.drop(df[df.Data_2.str.count(",")==138].index, inplace=True)
  df.drop(df[df.Data.str.count(",")==138].index, inplace=True)
  return df